# Generated by Django 3.2.5 on 2021-07-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome da marca')),
                ('origem', models.CharField(max_length=250, verbose_name='Origem')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do carro')),
                ('km_por_galao', models.IntegerField(verbose_name='Litros por galão')),
                ('cavalo_de_forca', models.IntegerField(verbose_name='Cavalo de força')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('aceleracao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Acelaracão')),
                ('data_fabricacao', models.DateTimeField(verbose_name='Data de fabricação')),
                ('origem', models.CharField(max_length=15, verbose_name='Origem')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marca')),
            ],
        ),
    ]
